// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package dtdiff is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	ProtoReplica
	ProtoEntry
*/
package dtdiff

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type ProtoReplica struct {
	Version          *uint32  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	CreatedBy        *string  `protobuf:"bytes,2,opt,name=createdBy" json:"createdBy,omitempty"`
	Identity         *string  `protobuf:"bytes,3,opt,name=identity" json:"identity,omitempty"`
	Generation       *uint64  `protobuf:"varint,4,opt,name=generation" json:"generation,omitempty"`
	KnowledgeKeys    []string `protobuf:"bytes,5,rep,name=knowledgeKeys" json:"knowledgeKeys,omitempty"`
	KnowledgeValues  []uint64 `protobuf:"varint,6,rep,name=knowledgeValues" json:"knowledgeValues,omitempty"`
	OptionKeys       []string `protobuf:"bytes,7,rep,name=optionKeys" json:"optionKeys,omitempty"`
	OptionValues     []string `protobuf:"bytes,8,rep,name=optionValues" json:"optionValues,omitempty"`
	Hash             *string  `protobuf:"bytes,9,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ProtoReplica) Reset()                    { *m = ProtoReplica{} }
func (m *ProtoReplica) String() string            { return proto.CompactTextString(m) }
func (*ProtoReplica) ProtoMessage()               {}
func (*ProtoReplica) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtoReplica) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *ProtoReplica) GetCreatedBy() string {
	if m != nil && m.CreatedBy != nil {
		return *m.CreatedBy
	}
	return ""
}

func (m *ProtoReplica) GetIdentity() string {
	if m != nil && m.Identity != nil {
		return *m.Identity
	}
	return ""
}

func (m *ProtoReplica) GetGeneration() uint64 {
	if m != nil && m.Generation != nil {
		return *m.Generation
	}
	return 0
}

func (m *ProtoReplica) GetKnowledgeKeys() []string {
	if m != nil {
		return m.KnowledgeKeys
	}
	return nil
}

func (m *ProtoReplica) GetKnowledgeValues() []uint64 {
	if m != nil {
		return m.KnowledgeValues
	}
	return nil
}

func (m *ProtoReplica) GetOptionKeys() []string {
	if m != nil {
		return m.OptionKeys
	}
	return nil
}

func (m *ProtoReplica) GetOptionValues() []string {
	if m != nil {
		return m.OptionValues
	}
	return nil
}

func (m *ProtoReplica) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

type ProtoEntry struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type             *uint32 `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	ModTime          *int64  `protobuf:"zigzag64,3,opt,name=modTime" json:"modTime,omitempty"`
	Size             *uint64 `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	Identity         *uint32 `protobuf:"varint,5,opt,name=identity" json:"identity,omitempty"`
	Generation       *uint64 `protobuf:"varint,6,opt,name=generation" json:"generation,omitempty"`
	Mode             *uint32 `protobuf:"varint,7,opt,name=mode" json:"mode,omitempty"`
	HasMode          *uint32 `protobuf:"varint,8,opt,name=hasMode" json:"hasMode,omitempty"`
	HashType         *uint32 `protobuf:"varint,9,opt,name=hashType" json:"hashType,omitempty"`
	HashData         []byte  `protobuf:"bytes,10,opt,name=hashData" json:"hashData,omitempty"`
	Removed          *int64  `protobuf:"zigzag64,11,opt,name=removed" json:"removed,omitempty"`
	Fs               *uint64 `protobuf:"varint,12,opt,name=fs" json:"fs,omitempty"`
	IdInode          *uint64 `protobuf:"varint,13,opt,name=idInode" json:"idInode,omitempty"`
	IdGen            *uint64 `protobuf:"varint,14,opt,name=idGen" json:"idGen,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoEntry) Reset()                    { *m = ProtoEntry{} }
func (m *ProtoEntry) String() string            { return proto.CompactTextString(m) }
func (*ProtoEntry) ProtoMessage()               {}
func (*ProtoEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProtoEntry) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ProtoEntry) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *ProtoEntry) GetModTime() int64 {
	if m != nil && m.ModTime != nil {
		return *m.ModTime
	}
	return 0
}

func (m *ProtoEntry) GetSize() uint64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *ProtoEntry) GetIdentity() uint32 {
	if m != nil && m.Identity != nil {
		return *m.Identity
	}
	return 0
}

func (m *ProtoEntry) GetGeneration() uint64 {
	if m != nil && m.Generation != nil {
		return *m.Generation
	}
	return 0
}

func (m *ProtoEntry) GetMode() uint32 {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return 0
}

func (m *ProtoEntry) GetHasMode() uint32 {
	if m != nil && m.HasMode != nil {
		return *m.HasMode
	}
	return 0
}

func (m *ProtoEntry) GetHashType() uint32 {
	if m != nil && m.HashType != nil {
		return *m.HashType
	}
	return 0
}

func (m *ProtoEntry) GetHashData() []byte {
	if m != nil {
		return m.HashData
	}
	return nil
}

func (m *ProtoEntry) GetRemoved() int64 {
	if m != nil && m.Removed != nil {
		return *m.Removed
	}
	return 0
}

func (m *ProtoEntry) GetFs() uint64 {
	if m != nil && m.Fs != nil {
		return *m.Fs
	}
	return 0
}

func (m *ProtoEntry) GetIdInode() uint64 {
	if m != nil && m.IdInode != nil {
		return *m.IdInode
	}
	return 0
}

func (m *ProtoEntry) GetIdGen() uint64 {
	if m != nil && m.IdGen != nil {
		return *m.IdGen
	}
	return 0
}

func init() {
	proto.RegisterType((*ProtoReplica)(nil), "dtdiff.ProtoReplica")
	proto.RegisterType((*ProtoEntry)(nil), "dtdiff.ProtoEntry")
}

var fileDescriptor0 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x8f, 0xcd, 0x4a, 0x03, 0x31,
	0x10, 0xc7, 0xd9, 0x76, 0xfb, 0xb1, 0xe3, 0x6e, 0xab, 0x41, 0x31, 0xc7, 0xd2, 0x93, 0x27, 0x1f,
	0x42, 0x14, 0x11, 0x11, 0x44, 0x8a, 0xf7, 0xd0, 0x4c, 0xdb, 0x60, 0x37, 0x59, 0x36, 0xb1, 0xb2,
	0x3e, 0x9d, 0x2f, 0xe4, 0x3b, 0x38, 0x33, 0x2e, 0x52, 0x8f, 0xf9, 0xfd, 0x3f, 0xf2, 0x1f, 0x98,
	0xd5, 0x18, 0xa3, 0xd9, 0x62, 0xbc, 0x6e, 0xda, 0x90, 0x82, 0x1a, 0xdb, 0x64, 0xdd, 0x66, 0xb3,
	0xfc, 0xca, 0xa0, 0x7c, 0x66, 0xf2, 0x82, 0xcd, 0xde, 0xad, 0x8d, 0x9a, 0xc3, 0xe4, 0x80, 0x6d,
	0x74, 0xc1, 0xeb, 0x6c, 0x91, 0x5d, 0x55, 0xea, 0x0c, 0x8a, 0x75, 0x8b, 0x26, 0xa1, 0xbd, 0xe9,
	0xf4, 0x80, 0x50, 0xa1, 0x4e, 0x61, 0xea, 0x2c, 0xfa, 0xe4, 0x52, 0xa7, 0x87, 0x42, 0x14, 0xc0,
	0x16, 0x3d, 0xb6, 0x26, 0x71, 0x30, 0x27, 0x96, 0xab, 0x0b, 0xa8, 0xde, 0x7c, 0xf8, 0xd8, 0xa3,
	0xdd, 0xe2, 0x23, 0x76, 0x51, 0x8f, 0x16, 0x43, 0xb2, 0x5e, 0xc2, 0xfc, 0x0f, 0xbf, 0x9a, 0xfd,
	0x3b, 0x46, 0x3d, 0x26, 0x21, 0xe7, 0x8e, 0xd0, 0x70, 0x5e, 0xcc, 0x13, 0x31, 0x9f, 0x43, 0xf9,
	0xcb, 0x7a, 0xe7, 0x54, 0x68, 0x09, 0xf9, 0xce, 0xc4, 0x9d, 0x2e, 0xf8, 0xef, 0xe5, 0x77, 0x06,
	0x20, 0x27, 0xdc, 0xf9, 0xd4, 0x76, 0x2c, 0x7a, 0x53, 0xa3, 0xac, 0x17, 0x6b, 0xea, 0x1a, 0x94,
	0xe1, 0x15, 0x1f, 0x57, 0x07, 0xbb, 0x72, 0x24, 0xf3, 0x6e, 0xc5, 0x72, 0x74, 0x9f, 0xd8, 0x2f,
	0x3e, 0xbe, 0x6b, 0x24, 0x81, 0xff, 0x77, 0x8d, 0xc5, 0x45, 0x19, 0x2a, 0x41, 0x5a, 0xd8, 0x57,
	0xd2, 0x96, 0x27, 0x06, 0x53, 0x01, 0x54, 0xc2, 0xe3, 0x56, 0xfc, 0x6b, 0x71, 0x4c, 0x6e, 0x4d,
	0x32, 0x1a, 0x88, 0x94, 0x1c, 0x6a, 0xb1, 0x0e, 0x07, 0xb4, 0xfa, 0x44, 0x76, 0x00, 0x0c, 0x36,
	0x51, 0x97, 0xd2, 0x4f, 0xa2, 0xb3, 0x0f, 0x9e, 0x1b, 0x2b, 0x01, 0x15, 0x8c, 0x9c, 0xbd, 0x47,
	0xaf, 0x67, 0xfc, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0x72, 0x76, 0x6e, 0xb9, 0xcb, 0x01, 0x00,
	0x00,
}
