// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package dtdiff is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	ProtoReplica
	ProtoEntry
*/
package dtdiff

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type ProtoReplica struct {
	Version          *uint32  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	CreatedBy        *string  `protobuf:"bytes,2,opt,name=createdBy" json:"createdBy,omitempty"`
	Identity         *string  `protobuf:"bytes,3,opt,name=identity" json:"identity,omitempty"`
	Generation       *uint64  `protobuf:"varint,4,opt,name=generation" json:"generation,omitempty"`
	KnowledgeKeys    []string `protobuf:"bytes,5,rep,name=knowledgeKeys" json:"knowledgeKeys,omitempty"`
	KnowledgeValues  []uint64 `protobuf:"varint,6,rep,name=knowledgeValues" json:"knowledgeValues,omitempty"`
	OptionKeys       []string `protobuf:"bytes,7,rep,name=optionKeys" json:"optionKeys,omitempty"`
	OptionValues     []string `protobuf:"bytes,8,rep,name=optionValues" json:"optionValues,omitempty"`
	Hash             *string  `protobuf:"bytes,9,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ProtoReplica) Reset()                    { *m = ProtoReplica{} }
func (m *ProtoReplica) String() string            { return proto.CompactTextString(m) }
func (*ProtoReplica) ProtoMessage()               {}
func (*ProtoReplica) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtoReplica) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *ProtoReplica) GetCreatedBy() string {
	if m != nil && m.CreatedBy != nil {
		return *m.CreatedBy
	}
	return ""
}

func (m *ProtoReplica) GetIdentity() string {
	if m != nil && m.Identity != nil {
		return *m.Identity
	}
	return ""
}

func (m *ProtoReplica) GetGeneration() uint64 {
	if m != nil && m.Generation != nil {
		return *m.Generation
	}
	return 0
}

func (m *ProtoReplica) GetKnowledgeKeys() []string {
	if m != nil {
		return m.KnowledgeKeys
	}
	return nil
}

func (m *ProtoReplica) GetKnowledgeValues() []uint64 {
	if m != nil {
		return m.KnowledgeValues
	}
	return nil
}

func (m *ProtoReplica) GetOptionKeys() []string {
	if m != nil {
		return m.OptionKeys
	}
	return nil
}

func (m *ProtoReplica) GetOptionValues() []string {
	if m != nil {
		return m.OptionValues
	}
	return nil
}

func (m *ProtoReplica) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

type ProtoEntry struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type             *uint32 `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	ModTime          *int64  `protobuf:"zigzag64,3,opt,name=modTime" json:"modTime,omitempty"`
	Size             *uint64 `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	Identity         *uint32 `protobuf:"varint,5,opt,name=identity" json:"identity,omitempty"`
	Generation       *uint64 `protobuf:"varint,6,opt,name=generation" json:"generation,omitempty"`
	Mode             *uint32 `protobuf:"varint,7,opt,name=mode" json:"mode,omitempty"`
	HasMode          *uint32 `protobuf:"varint,8,opt,name=hasMode" json:"hasMode,omitempty"`
	HashType         *uint32 `protobuf:"varint,9,opt,name=hashType" json:"hashType,omitempty"`
	HashData         []byte  `protobuf:"bytes,10,opt,name=hashData" json:"hashData,omitempty"`
	Removed          *int64  `protobuf:"zigzag64,11,opt,name=removed" json:"removed,omitempty"`
	Inode            *uint64 `protobuf:"varint,12,opt,name=inode" json:"inode,omitempty"`
	Fs               *uint64 `protobuf:"varint,16,opt,name=fs" json:"fs,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoEntry) Reset()                    { *m = ProtoEntry{} }
func (m *ProtoEntry) String() string            { return proto.CompactTextString(m) }
func (*ProtoEntry) ProtoMessage()               {}
func (*ProtoEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProtoEntry) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ProtoEntry) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *ProtoEntry) GetModTime() int64 {
	if m != nil && m.ModTime != nil {
		return *m.ModTime
	}
	return 0
}

func (m *ProtoEntry) GetSize() uint64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *ProtoEntry) GetIdentity() uint32 {
	if m != nil && m.Identity != nil {
		return *m.Identity
	}
	return 0
}

func (m *ProtoEntry) GetGeneration() uint64 {
	if m != nil && m.Generation != nil {
		return *m.Generation
	}
	return 0
}

func (m *ProtoEntry) GetMode() uint32 {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return 0
}

func (m *ProtoEntry) GetHasMode() uint32 {
	if m != nil && m.HasMode != nil {
		return *m.HasMode
	}
	return 0
}

func (m *ProtoEntry) GetHashType() uint32 {
	if m != nil && m.HashType != nil {
		return *m.HashType
	}
	return 0
}

func (m *ProtoEntry) GetHashData() []byte {
	if m != nil {
		return m.HashData
	}
	return nil
}

func (m *ProtoEntry) GetRemoved() int64 {
	if m != nil && m.Removed != nil {
		return *m.Removed
	}
	return 0
}

func (m *ProtoEntry) GetInode() uint64 {
	if m != nil && m.Inode != nil {
		return *m.Inode
	}
	return 0
}

func (m *ProtoEntry) GetFs() uint64 {
	if m != nil && m.Fs != nil {
		return *m.Fs
	}
	return 0
}

func init() {
	proto.RegisterType((*ProtoReplica)(nil), "dtdiff.ProtoReplica")
	proto.RegisterType((*ProtoEntry)(nil), "dtdiff.ProtoEntry")
}

var fileDescriptor0 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x8f, 0xcd, 0x4e, 0xc3, 0x30,
	0x10, 0x84, 0x95, 0x36, 0xfd, 0xc9, 0x92, 0xd0, 0x62, 0x81, 0xf0, 0xb1, 0xea, 0x89, 0x13, 0x0f,
	0x81, 0xe0, 0x84, 0x90, 0x10, 0xaa, 0xb8, 0x5b, 0xf5, 0x26, 0xb5, 0x48, 0xec, 0xc8, 0x36, 0x45,
	0xe1, 0xe9, 0x78, 0x10, 0x1e, 0x06, 0xef, 0x12, 0xa1, 0x72, 0xb3, 0xbe, 0x9d, 0x19, 0xcf, 0xc0,
	0x79, 0x87, 0x21, 0xa8, 0x06, 0xc3, 0x6d, 0xef, 0x5d, 0x74, 0x62, 0xae, 0xa3, 0x36, 0x75, 0xbd,
	0xfd, 0xca, 0xa0, 0x7c, 0x26, 0xf2, 0x82, 0x7d, 0x6b, 0xf6, 0x4a, 0xac, 0x60, 0x71, 0x44, 0x1f,
	0x8c, 0xb3, 0x32, 0xdb, 0x64, 0x37, 0x95, 0xb8, 0x80, 0x62, 0xef, 0x51, 0x45, 0xd4, 0x77, 0x83,
	0x9c, 0x24, 0x54, 0x88, 0x35, 0x2c, 0x8d, 0x46, 0x1b, 0x4d, 0x1c, 0xe4, 0x94, 0x89, 0x00, 0x68,
	0xd0, 0xa2, 0x57, 0x91, 0x8c, 0x79, 0x62, 0xb9, 0xb8, 0x82, 0xea, 0xcd, 0xba, 0x8f, 0x16, 0x75,
	0x83, 0x8f, 0x38, 0x04, 0x39, 0xdb, 0x4c, 0x93, 0xf4, 0x1a, 0x56, 0x7f, 0xf8, 0x55, 0xb5, 0xef,
	0x18, 0xe4, 0x3c, 0x1d, 0x72, 0xca, 0x70, 0x3d, 0xf9, 0x59, 0xbc, 0x60, 0xf1, 0x25, 0x94, 0xbf,
	0x6c, 0x54, 0x2e, 0x99, 0x96, 0x90, 0x1f, 0x54, 0x38, 0xc8, 0x82, 0xfe, 0xde, 0x7e, 0x67, 0x00,
	0x3c, 0xe1, 0xc1, 0x46, 0x3f, 0xd0, 0xd1, 0xaa, 0x0e, 0xb9, 0x3d, 0x4b, 0xe3, 0xd0, 0x23, 0x17,
	0xaf, 0x68, 0x5c, 0xe7, 0xf4, 0xce, 0xa4, 0x33, 0xf5, 0x16, 0x74, 0x0e, 0xe6, 0x13, 0xc7, 0xc6,
	0xa7, 0xbb, 0x66, 0x6c, 0xf8, 0xbf, 0x6b, 0xce, 0xaa, 0xe4, 0x49, 0x21, 0x98, 0x1a, 0x8e, 0x91,
	0xa9, 0xcb, 0x13, 0x81, 0x25, 0x83, 0x14, 0x42, 0xe5, 0x76, 0xf4, 0x6b, 0x71, 0x4a, 0xee, 0x55,
	0x54, 0x12, 0x12, 0x29, 0xc9, 0xe4, 0xb1, 0x73, 0x47, 0xd4, 0xf2, 0x8c, 0x7b, 0x54, 0x30, 0x33,
	0x96, 0x32, 0x4a, 0xfe, 0x02, 0x60, 0x52, 0x07, 0xb9, 0xa6, 0xf7, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x3e, 0xeb, 0xb6, 0xb8, 0xba, 0x01, 0x00, 0x00,
}
