// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package dtdiff is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	ProtoReplica
	ProtoEntry
*/
package dtdiff

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type ProtoReplica struct {
	Version          *uint32  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	CreatedBy        *string  `protobuf:"bytes,2,opt,name=createdBy" json:"createdBy,omitempty"`
	Identity         *string  `protobuf:"bytes,3,opt,name=identity" json:"identity,omitempty"`
	Generation       *uint64  `protobuf:"varint,4,opt,name=generation" json:"generation,omitempty"`
	KnowledgeKeys    []string `protobuf:"bytes,5,rep,name=knowledgeKeys" json:"knowledgeKeys,omitempty"`
	KnowledgeValues  []uint64 `protobuf:"varint,6,rep,name=knowledgeValues" json:"knowledgeValues,omitempty"`
	OptionKeys       []string `protobuf:"bytes,7,rep,name=optionKeys" json:"optionKeys,omitempty"`
	OptionValues     []string `protobuf:"bytes,8,rep,name=optionValues" json:"optionValues,omitempty"`
	Hash             *string  `protobuf:"bytes,9,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ProtoReplica) Reset()                    { *m = ProtoReplica{} }
func (m *ProtoReplica) String() string            { return proto.CompactTextString(m) }
func (*ProtoReplica) ProtoMessage()               {}
func (*ProtoReplica) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtoReplica) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *ProtoReplica) GetCreatedBy() string {
	if m != nil && m.CreatedBy != nil {
		return *m.CreatedBy
	}
	return ""
}

func (m *ProtoReplica) GetIdentity() string {
	if m != nil && m.Identity != nil {
		return *m.Identity
	}
	return ""
}

func (m *ProtoReplica) GetGeneration() uint64 {
	if m != nil && m.Generation != nil {
		return *m.Generation
	}
	return 0
}

func (m *ProtoReplica) GetKnowledgeKeys() []string {
	if m != nil {
		return m.KnowledgeKeys
	}
	return nil
}

func (m *ProtoReplica) GetKnowledgeValues() []uint64 {
	if m != nil {
		return m.KnowledgeValues
	}
	return nil
}

func (m *ProtoReplica) GetOptionKeys() []string {
	if m != nil {
		return m.OptionKeys
	}
	return nil
}

func (m *ProtoReplica) GetOptionValues() []string {
	if m != nil {
		return m.OptionValues
	}
	return nil
}

func (m *ProtoReplica) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

type ProtoEntry struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type             *uint32 `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	ModTime          *int64  `protobuf:"zigzag64,3,opt,name=modTime" json:"modTime,omitempty"`
	Size             *uint64 `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	Identity         *uint32 `protobuf:"varint,5,opt,name=identity" json:"identity,omitempty"`
	Generation       *uint64 `protobuf:"varint,6,opt,name=generation" json:"generation,omitempty"`
	Mode             *uint32 `protobuf:"varint,7,opt,name=mode" json:"mode,omitempty"`
	HasMode          *uint32 `protobuf:"varint,8,opt,name=hasMode" json:"hasMode,omitempty"`
	HashType         *uint32 `protobuf:"varint,9,opt,name=hashType" json:"hashType,omitempty"`
	HashData         []byte  `protobuf:"bytes,10,opt,name=hashData" json:"hashData,omitempty"`
	Removed          *int64  `protobuf:"zigzag64,11,opt,name=removed" json:"removed,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoEntry) Reset()                    { *m = ProtoEntry{} }
func (m *ProtoEntry) String() string            { return proto.CompactTextString(m) }
func (*ProtoEntry) ProtoMessage()               {}
func (*ProtoEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProtoEntry) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ProtoEntry) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *ProtoEntry) GetModTime() int64 {
	if m != nil && m.ModTime != nil {
		return *m.ModTime
	}
	return 0
}

func (m *ProtoEntry) GetSize() uint64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *ProtoEntry) GetIdentity() uint32 {
	if m != nil && m.Identity != nil {
		return *m.Identity
	}
	return 0
}

func (m *ProtoEntry) GetGeneration() uint64 {
	if m != nil && m.Generation != nil {
		return *m.Generation
	}
	return 0
}

func (m *ProtoEntry) GetMode() uint32 {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return 0
}

func (m *ProtoEntry) GetHasMode() uint32 {
	if m != nil && m.HasMode != nil {
		return *m.HasMode
	}
	return 0
}

func (m *ProtoEntry) GetHashType() uint32 {
	if m != nil && m.HashType != nil {
		return *m.HashType
	}
	return 0
}

func (m *ProtoEntry) GetHashData() []byte {
	if m != nil {
		return m.HashData
	}
	return nil
}

func (m *ProtoEntry) GetRemoved() int64 {
	if m != nil && m.Removed != nil {
		return *m.Removed
	}
	return 0
}

func init() {
	proto.RegisterType((*ProtoReplica)(nil), "dtdiff.ProtoReplica")
	proto.RegisterType((*ProtoEntry)(nil), "dtdiff.ProtoEntry")
}

var fileDescriptor0 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x8f, 0xc1, 0x4e, 0xc3, 0x30,
	0x0c, 0x86, 0x55, 0xd6, 0x75, 0xad, 0x69, 0x19, 0x44, 0x20, 0x72, 0x9c, 0x76, 0xe2, 0xc4, 0x43,
	0x20, 0x38, 0x21, 0x24, 0x84, 0x26, 0xee, 0xd1, 0xe2, 0x75, 0x11, 0x6d, 0x52, 0x25, 0x61, 0xa8,
	0x3c, 0x1d, 0xbc, 0x19, 0xb1, 0xa9, 0xd0, 0xb8, 0x7e, 0xfe, 0x7f, 0xfb, 0x33, 0x9c, 0xf5, 0x18,
	0x82, 0x6a, 0x31, 0xdc, 0x0e, 0xde, 0x45, 0x27, 0x0a, 0x1d, 0xb5, 0xd9, 0xed, 0xd6, 0x5f, 0x19,
	0xd4, 0xcf, 0x44, 0x5e, 0x70, 0xe8, 0xcc, 0x56, 0x89, 0x25, 0x2c, 0x0e, 0xe8, 0x83, 0x71, 0x56,
	0x66, 0xab, 0xec, 0xa6, 0x11, 0x17, 0x50, 0x6d, 0x3d, 0xaa, 0x88, 0xfa, 0x6e, 0x94, 0x27, 0x09,
	0x55, 0xe2, 0x1c, 0x4a, 0xa3, 0xd1, 0x46, 0x13, 0x47, 0x39, 0x63, 0x22, 0x00, 0x5a, 0xb4, 0xe8,
	0x55, 0xa4, 0x62, 0x9e, 0x58, 0x2e, 0xae, 0xa0, 0x79, 0xb3, 0xee, 0xa3, 0x43, 0xdd, 0xe2, 0x23,
	0x8e, 0x41, 0xce, 0x57, 0xb3, 0x14, 0xbd, 0x86, 0xe5, 0x1f, 0x7e, 0x55, 0xdd, 0x3b, 0x06, 0x59,
	0xa4, 0x41, 0x4e, 0x3b, 0xdc, 0x40, 0x7d, 0x0e, 0x2f, 0x38, 0x7c, 0x09, 0xf5, 0x2f, 0x9b, 0x92,
	0x25, 0xd3, 0x1a, 0xf2, 0xbd, 0x0a, 0x7b, 0x59, 0xd1, 0xed, 0xf5, 0x77, 0x06, 0xc0, 0x2f, 0x3c,
	0xd8, 0xe8, 0x47, 0x1a, 0x5a, 0xd5, 0x23, 0xdb, 0x73, 0x34, 0x8e, 0x03, 0xb2, 0x78, 0x43, 0xcf,
	0xf5, 0x4e, 0x6f, 0x4c, 0x1a, 0x93, 0xb7, 0xa0, 0x71, 0x30, 0x9f, 0x38, 0x19, 0x1f, 0xff, 0x35,
	0xe7, 0xc2, 0xff, 0xbf, 0x0a, 0x4e, 0xa5, 0x4e, 0x5a, 0x82, 0xc9, 0x70, 0x5a, 0x99, 0x5c, 0x9e,
	0x08, 0x94, 0x0c, 0xd2, 0x12, 0x92, 0xdb, 0xd0, 0xd5, 0xea, 0x98, 0xdc, 0xab, 0xa8, 0x24, 0x24,
	0x52, 0x53, 0xc9, 0x63, 0xef, 0x0e, 0xa8, 0xe5, 0x29, 0x79, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xe3, 0x24, 0x3b, 0x51, 0x9f, 0x01, 0x00, 0x00,
}
