// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package remote is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	FileInfo
	ScanOptions
	Error
	Request
	Response
*/
package remote

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Command int32

const (
	Command_NONE       Command = 0
	Command_CLOSE      Command = 1
	Command_DATA       Command = 2
	Command_SCAN       Command = 3
	Command_SCANOPTS   Command = 4
	Command_MKDIR      Command = 10
	Command_REMOVE     Command = 11
	Command_CREATE     Command = 12
	Command_UPDATE     Command = 13
	Command_COPYSRC    Command = 14
	Command_CREATELINK Command = 15
	Command_UPDATELINK Command = 16
	Command_READLINK   Command = 17
	Command_CHMOD      Command = 18
	Command_GETFILE    Command = 20
	Command_SETFILE    Command = 21
	// testing commands
	Command_PUTFILE Command = 30
	Command_INFO    Command = 31
)

var Command_name = map[int32]string{
	0:  "NONE",
	1:  "CLOSE",
	2:  "DATA",
	3:  "SCAN",
	4:  "SCANOPTS",
	10: "MKDIR",
	11: "REMOVE",
	12: "CREATE",
	13: "UPDATE",
	14: "COPYSRC",
	15: "CREATELINK",
	16: "UPDATELINK",
	17: "READLINK",
	18: "CHMOD",
	20: "GETFILE",
	21: "SETFILE",
	30: "PUTFILE",
	31: "INFO",
}
var Command_value = map[string]int32{
	"NONE":       0,
	"CLOSE":      1,
	"DATA":       2,
	"SCAN":       3,
	"SCANOPTS":   4,
	"MKDIR":      10,
	"REMOVE":     11,
	"CREATE":     12,
	"UPDATE":     13,
	"COPYSRC":    14,
	"CREATELINK": 15,
	"UPDATELINK": 16,
	"READLINK":   17,
	"CHMOD":      18,
	"GETFILE":    20,
	"SETFILE":    21,
	"PUTFILE":    30,
	"INFO":       31,
}

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}
func (x Command) String() string {
	return proto.EnumName(Command_name, int32(x))
}
func (x *Command) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Command_value, data, "Command")
	if err != nil {
		return err
	}
	*x = Command(value)
	return nil
}
func (Command) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// See TYPE_* constants in tree/tree.go
type FileType int32

const (
	FileType_UNKNOWN   FileType = 0
	FileType_REGULAR   FileType = 1
	FileType_DIRECTORY FileType = 2
)

var FileType_name = map[int32]string{
	0: "UNKNOWN",
	1: "REGULAR",
	2: "DIRECTORY",
}
var FileType_value = map[string]int32{
	"UNKNOWN":   0,
	"REGULAR":   1,
	"DIRECTORY": 2,
}

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}
func (x FileType) String() string {
	return proto.EnumName(FileType_name, int32(x))
}
func (x *FileType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FileType_value, data, "FileType")
	if err != nil {
		return err
	}
	*x = FileType(value)
	return nil
}
func (FileType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type DataStatus int32

const (
	DataStatus_NORMAL DataStatus = 0
	DataStatus_FINISH DataStatus = 1
	DataStatus_CANCEL DataStatus = 2
)

var DataStatus_name = map[int32]string{
	0: "NORMAL",
	1: "FINISH",
	2: "CANCEL",
}
var DataStatus_value = map[string]int32{
	"NORMAL": 0,
	"FINISH": 1,
	"CANCEL": 2,
}

func (x DataStatus) Enum() *DataStatus {
	p := new(DataStatus)
	*p = x
	return p
}
func (x DataStatus) String() string {
	return proto.EnumName(DataStatus_name, int32(x))
}
func (x *DataStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DataStatus_value, data, "DataStatus")
	if err != nil {
		return err
	}
	*x = DataStatus(value)
	return nil
}
func (DataStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ErrorType int32

const (
	ErrorType_ERR_OTHER      ErrorType = 0
	ErrorType_ERR_NOTFOUND   ErrorType = 1
	ErrorType_ERR_FOUND      ErrorType = 2
	ErrorType_ERR_CHANGED    ErrorType = 3
	ErrorType_ERR_NO_DIR     ErrorType = 10
	ErrorType_ERR_NO_REGULAR ErrorType = 11
	ErrorType_ERR_NO_SYMLINK ErrorType = 12
)

var ErrorType_name = map[int32]string{
	0:  "ERR_OTHER",
	1:  "ERR_NOTFOUND",
	2:  "ERR_FOUND",
	3:  "ERR_CHANGED",
	10: "ERR_NO_DIR",
	11: "ERR_NO_REGULAR",
	12: "ERR_NO_SYMLINK",
}
var ErrorType_value = map[string]int32{
	"ERR_OTHER":      0,
	"ERR_NOTFOUND":   1,
	"ERR_FOUND":      2,
	"ERR_CHANGED":    3,
	"ERR_NO_DIR":     10,
	"ERR_NO_REGULAR": 11,
	"ERR_NO_SYMLINK": 12,
}

func (x ErrorType) Enum() *ErrorType {
	p := new(ErrorType)
	*p = x
	return p
}
func (x ErrorType) String() string {
	return proto.EnumName(ErrorType_name, int32(x))
}
func (x *ErrorType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorType_value, data, "ErrorType")
	if err != nil {
		return err
	}
	*x = ErrorType(value)
	return nil
}
func (ErrorType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type FileInfo struct {
	Path             []string  `protobuf:"bytes,1,rep,name=path" json:"path,omitempty"`
	Type             *FileType `protobuf:"varint,2,opt,name=type,enum=remote.FileType" json:"type,omitempty"`
	Mode             *uint32   `protobuf:"varint,3,opt,name=mode" json:"mode,omitempty"`
	HasMode          *uint32   `protobuf:"varint,4,opt,name=hasMode" json:"hasMode,omitempty"`
	ModTime          *int64    `protobuf:"zigzag64,5,opt,name=modTime" json:"modTime,omitempty"`
	Size             *int64    `protobuf:"zigzag64,6,opt,name=size" json:"size,omitempty"`
	Hash             []byte    `protobuf:"bytes,7,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *FileInfo) Reset()                    { *m = FileInfo{} }
func (m *FileInfo) String() string            { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()               {}
func (*FileInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FileInfo) GetPath() []string {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *FileInfo) GetType() FileType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return FileType_UNKNOWN
}

func (m *FileInfo) GetMode() uint32 {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return 0
}

func (m *FileInfo) GetHasMode() uint32 {
	if m != nil && m.HasMode != nil {
		return *m.HasMode
	}
	return 0
}

func (m *FileInfo) GetModTime() int64 {
	if m != nil && m.ModTime != nil {
		return *m.ModTime
	}
	return 0
}

func (m *FileInfo) GetSize() int64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *FileInfo) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type ScanOptions struct {
	Ignore           []string `protobuf:"bytes,1,rep,name=ignore" json:"ignore,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ScanOptions) Reset()                    { *m = ScanOptions{} }
func (m *ScanOptions) String() string            { return proto.CompactTextString(m) }
func (*ScanOptions) ProtoMessage()               {}
func (*ScanOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ScanOptions) GetIgnore() []string {
	if m != nil {
		return m.Ignore
	}
	return nil
}

type Error struct {
	Type             *ErrorType `protobuf:"varint,1,opt,name=type,enum=remote.ErrorType" json:"type,omitempty"`
	Message          *string    `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Error) GetType() ErrorType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ErrorType_ERR_OTHER
}

func (m *Error) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type Request struct {
	Command          *Command    `protobuf:"varint,1,opt,name=command,enum=remote.Command" json:"command,omitempty"`
	RequestId        *uint64     `protobuf:"varint,2,opt,name=requestId" json:"requestId,omitempty"`
	FileInfo1        *FileInfo   `protobuf:"bytes,3,opt,name=fileInfo1" json:"fileInfo1,omitempty"`
	FileInfo2        *FileInfo   `protobuf:"bytes,4,opt,name=fileInfo2" json:"fileInfo2,omitempty"`
	Name             *string     `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	Data             []byte      `protobuf:"bytes,6,opt,name=data" json:"data,omitempty"`
	Status           *DataStatus `protobuf:"varint,7,opt,name=status,enum=remote.DataStatus" json:"status,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Request) GetCommand() Command {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return Command_NONE
}

func (m *Request) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *Request) GetFileInfo1() *FileInfo {
	if m != nil {
		return m.FileInfo1
	}
	return nil
}

func (m *Request) GetFileInfo2() *FileInfo {
	if m != nil {
		return m.FileInfo2
	}
	return nil
}

func (m *Request) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Request) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Request) GetStatus() DataStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return DataStatus_NORMAL
}

type Response struct {
	Command          *Command  `protobuf:"varint,1,opt,name=command,enum=remote.Command" json:"command,omitempty"`
	RequestId        *uint64   `protobuf:"varint,2,opt,name=requestId" json:"requestId,omitempty"`
	Error            *Error    `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	FileInfo         *FileInfo `protobuf:"bytes,4,opt,name=fileInfo" json:"fileInfo,omitempty"`
	ParentInfo       *FileInfo `protobuf:"bytes,5,opt,name=parentInfo" json:"parentInfo,omitempty"`
	Data             []byte    `protobuf:"bytes,6,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Response) GetCommand() Command {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return Command_NONE
}

func (m *Response) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetFileInfo() *FileInfo {
	if m != nil {
		return m.FileInfo
	}
	return nil
}

func (m *Response) GetParentInfo() *FileInfo {
	if m != nil {
		return m.ParentInfo
	}
	return nil
}

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*FileInfo)(nil), "remote.FileInfo")
	proto.RegisterType((*ScanOptions)(nil), "remote.ScanOptions")
	proto.RegisterType((*Error)(nil), "remote.Error")
	proto.RegisterType((*Request)(nil), "remote.Request")
	proto.RegisterType((*Response)(nil), "remote.Response")
	proto.RegisterEnum("remote.Command", Command_name, Command_value)
	proto.RegisterEnum("remote.FileType", FileType_name, FileType_value)
	proto.RegisterEnum("remote.DataStatus", DataStatus_name, DataStatus_value)
	proto.RegisterEnum("remote.ErrorType", ErrorType_name, ErrorType_value)
}

var fileDescriptor0 = []byte{
	// 624 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x25, 0x69, 0xbe, 0x3c, 0xf9, 0xe8, 0x76, 0x05, 0x52, 0x0e, 0xd0, 0x56, 0x81, 0x43, 0xd5,
	0x43, 0x05, 0xe5, 0xc4, 0xd1, 0xb2, 0x37, 0x8d, 0xd5, 0x64, 0x37, 0x5a, 0x3b, 0xa0, 0x9e, 0x2a,
	0xab, 0xd9, 0xb6, 0x91, 0x88, 0x6d, 0x6c, 0xf7, 0x00, 0x67, 0xfe, 0x12, 0xff, 0x81, 0x5f, 0xc2,
	0xef, 0x60, 0x76, 0xd7, 0x56, 0x5a, 0x89, 0x5e, 0xb8, 0xcd, 0x9b, 0x7d, 0x33, 0xfb, 0xde, 0xb3,
	0x17, 0x46, 0x5b, 0x55, 0x14, 0xf1, 0x9d, 0x2a, 0xce, 0xb2, 0x3c, 0x2d, 0x53, 0xda, 0xc9, 0xd5,
	0x36, 0x2d, 0xd5, 0xe4, 0x67, 0x03, 0x7a, 0xd3, 0xcd, 0x57, 0x15, 0x24, 0xb7, 0x29, 0x1d, 0x40,
	0x2b, 0x8b, 0xcb, 0xfb, 0x71, 0xe3, 0x78, 0xef, 0xc4, 0xa1, 0x87, 0xd0, 0x2a, 0xbf, 0x67, 0x6a,
	0xdc, 0x3c, 0x6e, 0x9c, 0x8c, 0xce, 0xc9, 0x99, 0x9d, 0x38, 0xd3, 0xec, 0x08, 0xfb, 0x9a, 0xbd,
	0x4d, 0xd7, 0x6a, 0xbc, 0x87, 0xe7, 0x43, 0xba, 0x0f, 0xdd, 0xfb, 0xb8, 0x58, 0xe8, 0x46, 0xab,
	0x6e, 0xe0, 0x71, 0xb4, 0xd9, 0xaa, 0x71, 0x1b, 0x1b, 0x54, 0xf3, 0x8b, 0xcd, 0x0f, 0x35, 0xee,
	0xd4, 0x08, 0xf9, 0xf7, 0xe3, 0x2e, 0xa2, 0xc1, 0xe4, 0x0d, 0xf4, 0xc3, 0x9b, 0x38, 0x11, 0x59,
	0xb9, 0x49, 0x93, 0x82, 0x8e, 0xa0, 0xb3, 0xb9, 0x4b, 0xd2, 0x5c, 0x59, 0x29, 0x93, 0x4f, 0xd0,
	0x66, 0x79, 0x9e, 0xe6, 0xf4, 0xa8, 0xd2, 0xd4, 0x30, 0x9a, 0x0e, 0x6a, 0x4d, 0xe6, 0xd0, 0x88,
	0xd2, 0xb7, 0x5a, 0xa7, 0x46, 0xb7, 0x33, 0xf9, 0xdd, 0x80, 0xae, 0x54, 0xdf, 0x1e, 0x54, 0x51,
	0xd2, 0x63, 0xe8, 0xde, 0xa4, 0xdb, 0x6d, 0x9c, 0xac, 0xab, 0x05, 0xfb, 0xf5, 0x02, 0xcf, 0xb6,
	0xe9, 0x01, 0x38, 0xb9, 0x25, 0x07, 0x6b, 0xb3, 0xa0, 0x45, 0xdf, 0x82, 0x73, 0x5b, 0x05, 0xf4,
	0xc1, 0x78, 0xed, 0x3f, 0xcd, 0xc2, 0x24, 0xf7, 0x88, 0x74, 0x6e, 0xfc, 0xff, 0x8b, 0x84, 0x96,
	0x93, 0xb8, 0x8a, 0xc3, 0xd1, 0x68, 0x1d, 0x97, 0xb1, 0x89, 0x63, 0x40, 0x27, 0xd0, 0x29, 0xca,
	0xb8, 0x7c, 0x28, 0x4c, 0x20, 0xa3, 0x73, 0x5a, 0x4f, 0xfb, 0xc8, 0x09, 0xcd, 0xc9, 0xe4, 0x17,
	0x7e, 0x2b, 0xa9, 0x8a, 0x0c, 0x13, 0x52, 0xff, 0xe7, 0xe5, 0x35, 0xb4, 0x95, 0x8e, 0xaa, 0xf2,
	0x31, 0x7c, 0x92, 0x1f, 0x6a, 0xe8, 0xd5, 0x26, 0x9e, 0xf5, 0xf0, 0x0e, 0x20, 0x8b, 0x73, 0x95,
	0x94, 0x86, 0xd5, 0x7e, 0xde, 0xe9, 0xce, 0xdb, 0xe9, 0x1f, 0xfc, 0x04, 0xb5, 0xa8, 0x1e, 0xb4,
	0xb8, 0xe0, 0x8c, 0xbc, 0xa0, 0x0e, 0xb4, 0xbd, 0xb9, 0x08, 0x19, 0x69, 0xe8, 0xa6, 0xef, 0x46,
	0x2e, 0x69, 0xea, 0x2a, 0xf4, 0x5c, 0x4e, 0xf6, 0x70, 0x45, 0x4f, 0x57, 0x62, 0x19, 0x85, 0xa4,
	0xa5, 0xc9, 0x8b, 0x4b, 0x3f, 0x90, 0x04, 0x28, 0x40, 0x47, 0xb2, 0x85, 0xf8, 0xcc, 0x48, 0x5f,
	0xd7, 0x9e, 0x64, 0x6e, 0xc4, 0xc8, 0x40, 0xd7, 0xab, 0xa5, 0xaf, 0xeb, 0x21, 0xed, 0xe3, 0x85,
	0x62, 0x79, 0x15, 0x4a, 0x8f, 0x8c, 0xf0, 0x67, 0x02, 0x4b, 0x9a, 0x07, 0xfc, 0x92, 0xec, 0x6b,
	0x6c, 0x89, 0x06, 0x13, 0x7d, 0x13, 0x1e, 0xfb, 0x06, 0x1d, 0x18, 0x59, 0xb3, 0x85, 0xf0, 0x09,
	0xd5, 0x5b, 0x2e, 0x58, 0x34, 0x0d, 0xe6, 0x8c, 0xbc, 0xd4, 0x20, 0xac, 0xc0, 0x2b, 0x0d, 0x96,
	0x2b, 0x0b, 0x0e, 0xb5, 0xe6, 0x80, 0x4f, 0x05, 0x39, 0x3a, 0xfd, 0x68, 0xdf, 0x92, 0xf9, 0x11,
	0x91, 0xb2, 0xe2, 0x97, 0x5c, 0x7c, 0xe1, 0xe8, 0x15, 0x81, 0x64, 0x17, 0xab, 0xb9, 0x2b, 0xd1,
	0xed, 0x10, 0x1c, 0x74, 0xc2, 0xbc, 0x48, 0xc8, 0x2b, 0xd2, 0x3c, 0x7d, 0x0f, 0xb0, 0xfb, 0xc6,
	0xda, 0x05, 0x17, 0x72, 0xe1, 0xce, 0x71, 0x0a, 0xeb, 0x69, 0xc0, 0x83, 0x70, 0x86, 0x43, 0xda,
	0xa9, 0xcb, 0x3d, 0x36, 0xc7, 0x09, 0x7c, 0xb3, 0xce, 0xee, 0x8f, 0xc7, 0x75, 0x4c, 0xca, 0x6b,
	0x11, 0xcd, 0x98, 0xc4, 0x21, 0x02, 0x03, 0x0d, 0xb9, 0x88, 0xa6, 0x62, 0xc5, 0x7d, 0x7b, 0x9f,
	0xee, 0x58, 0xd8, 0xc4, 0x17, 0xd2, 0xd7, 0xd0, 0x9b, 0xb9, 0xfc, 0x82, 0xf9, 0x98, 0x34, 0xe6,
	0x61, 0x27, 0xae, 0x6d, 0xc0, 0x14, 0x46, 0x15, 0xae, 0x35, 0xf7, 0x1f, 0xf5, 0xc2, 0xab, 0x85,
	0x49, 0x6a, 0xf0, 0x37, 0x00, 0x00, 0xff, 0xff, 0x3a, 0xea, 0x5f, 0x33, 0x53, 0x04, 0x00, 0x00,
}
